[tool.poetry]
name = "projectsummarizer"
version = "0.1.0"
description = ""
authors = ["e_mamul <eugene@pufin.id>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.9"
nbformat = "^5.10.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
